### ISSUE TITLE
Getting ModuleNotFoundError: No module named 'django_admin_listfilter_dropdown'

### ISSUE THREAD

**Issue by sanshah1211** [NeCTAR-RC/bumblebee#7]
init compose service, getting below error in logs 
Traceback (most recent call last):
init-1  |   File "/env/bin/django-admin", line 8, in <module>
init-1  |     sys.exit(execute_from_command_line())
init-1  |   File "/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
init-1  |     utility.execute()
init-1  |   File "/env/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
init-1  |     django.setup()
init-1  |   File "/env/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
init-1  |     apps.populate(settings.INSTALLED_APPS)
init-1  |   File "/env/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
init-1  |     app_config = AppConfig.create(entry)
init-1  |   File "/env/lib/python3.9/site-packages/django/apps/config.py", line 224, in create
init-1  |     import_module(entry)
init-1  |   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
init-1  |     return _bootstrap._gcd_import(name[level:], package, level)
init-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
init-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
init-1  |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
init-1  | ModuleNotFoundError: No module named 'django_admin_listfilter_dropdown'

**Comment by sorrison** [comment]
Hi there, this package is listed in the requirements. maybe you need to reinstall? 
https://github.com/NeCTAR-RC/bumblebee/blob/master/requirements.txt#L28

**Comment by sanshah1211** [comment]
Let me try, thanks

**Comment by sanshah1211** [comment]
Issue resolved, thank you.
